### ISSUE TITLE
No extraction output

### ISSUE THREAD

**Issue by michaljirman** [macmade/dyld_cache_extract#1]
Hi @macmade, 
I've just tested your tool and it doesn't extract library/libraries from cache for --extract or -extract-all options. The --info option works just fine.
Could you please tell me how to use it?

Thank you.

**Comment by macmade** [comment]
Hi @Jirmi : )

Well, you're using it right, but unfortunately the extraction is not finished yet...
Not enough time to finish it at the moment...

I'll leave this issue open, I'll close it when the extraction work...

**Comment by macmade** [comment]
Well, should be working very soon... : )
