### ISSUE TITLE
#include <XS/PIMPL/Object.hpp> not found

### ISSUE THREAD

**Issue by liuxuan30** [macmade/dyld_cache_extract#3]
Is there any binary I can download instead of compile?
It reports #include <XS/PIMPL/Object.hpp> not found all the time and I don't know where is it.

**Comment by macmade** [comment]
You simply have to check out the submodules as well...

**Comment by malhal** [comment]
Submodules can't be checked out from the release version because it's not a git repo. I would suggest either making the release a binary or removing it and adding git checkout instructions to the readme.

**Comment by macmade** [comment]
Allright, there's now a pre-built app available : )
https://github.com/macmade/dyld_cache_extract/releases/tag/0.1.0

**Comment by malhal** [comment]
I should have also suggested including the source of the sub modules in the release version, that would have done the trick but I'd imagine most people after a release are happy with a binary

**Comment by macmade** [comment]
Yes, and the problem is that GitHub automatically generates the zip or tar files, but does not include the submodules... : (

So I'm afraid I can't provide complete source code download with submodules...
