### ISSUE TITLE
The file "dyld_shared_cache_arm64" is not a valid DYLD shared cache file.

### ISSUE THREAD

**Issue by kingcos** [macmade/dyld_cache_extract#5]
Hi, @macmade .

I found that is not worked for dyld_shared_cache_arm64, but worked for dyld_shared_cache_armv7s. I got the dyld_shared_cache from my Jailbroken iPhone 5s, on iOS 9.0.1.

- dyld_shared_cache_arm64

![screen shot 2018-09-09 at 12 13 15](https://user-images.githubusercontent.com/10249989/45261030-c36a9100-b429-11e8-980d-3d21b102b6b6.png)

- dyld_shared_cache_armv7s

![screen shot 2018-09-09 at 12 14 08](https://user-images.githubusercontent.com/10249989/45261033-de3d0580-b429-11e8-9543-012354f96d9e.png)

So is it doesn't support arm64 now? or some other reasons?

Thank you!

**Comment by macmade** [comment]
Closing as the project is now obsolete.  
Please take a look at https://github.com/macmade/dyld-cache-dump
