### ISSUE TITLE
Command ProcessPCH++ failed with a nonzero exit code

### ISSUE THREAD

**Issue by fly-will** [macmade/dyld_cache_extract#9]
when I complie with xcode, it report this.

In file included from /Users/perf/Documents/GitHub/dyld_cache_extract/dyld_cache_extract/DCE.pch:33:
Submodules/SeriousCode/clang-warnings.h:453:32: fatal error: unknown warning group '-Wfallback', ignored [-Wunknown-warning-option]
#pragma clang diagnostic fatal "-Wfallback"
                               ^
1 error generated.
Command ProcessPCH++ failed with a nonzero exit code

**Comment by macmade** [comment]
Closing as the project is now obsolete.  
Please take a look at https://github.com/macmade/dyld-cache-dump
